### ISSUE TITLE
[fix] iOS 16으로 업데이트 하면서 생긴 프레임 드랍 문제

### ISSUE THREAD

**Issue by hminkim** [hminkim/ARShootingGame#3]
### 작업에 대한 간단한 설명
- iOS 16으로 업데이트 되면서 갑자기 잘되던 ARKit의 프레임 드랍이 나타나는 현상 원인 파악
    - [애플 개발자 포럼](https://developer.apple.com/forums/thread/717394), [외국 기사](https://piunikaweb.com/2022/10/21/iphone-screen-or-animation-stutter-after-ios-16-update/)를 보면 이런 문제가 종종 발생하는 것 같음
- 원인에 대한 파악이 완료되었을 경우 버그 픽스 작업
    - 프로젝트 기간에 맞춰 일주일만에 만들면서 제대로 비동기 처리가 설계되지 않은 부분이 없는지 확인

### TODO
- [ ] 프레임 드랍 원인 파악
- [ ] 비동기 처리 설계 재확인
    - [ ] 다른 원인이 있다면 파악 후 문제 해결
